# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
x=s.split()
print(x)


['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [4]:
txt1="The diameter of {fname} is {fname1} kilometers.".format(fname="Earth",fname1="12742")
print(txt1)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
array1=d['k1'][3]['tricky'][3]['target'][3]
print(array1)


hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [13]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [16]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [21]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
x=np.concatenate((a, b), axis=None)
print(x)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [26]:
import numpy as np
import pandas as pd
data = np.array([[5.8, 2.8], [6.0, 2.2]])
dataset = pd.DataFrame({'Column1': data[:, 0], 'Column2': data[:, 1]})
print(dataset)

   Column1  Column2
0      5.8      2.8
1      6.0      2.2


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [30]:
class Date:
    def __init__(self, d, m, y):
        self.d = d
        self.m = m
        self.y = y

monthDays = [31, 28, 31, 30, 31, 30,
             31, 31, 30, 31, 30, 31]
 
def countLeapYears(d):
 
    years = d.y
    if (d.m <= 2):
        years -= 1
 
   
    return int(years / 4) - int(years / 100) + int(years / 400)
 
def getDifference(dt1, dt2):
 
    
    n1 = dt1.y * 365 + dt1.d
 
  
    for i in range(0, dt1.m - 1):
        n1 += monthDays[i]
 
    n1 += countLeapYears(dt1)
 
    n2 = dt2.y * 365 + dt2.d
    for i in range(0, dt2.m - 1):
        n2 += monthDays[i]
    n2 += countLeapYears(dt2)
 
    
    return (n2 - n1)
 
dt1 = Date(13, 12, 2018)
dt2 = Date(25, 2, 2019)
 
print(getDifference(dt1, dt2), "days")    
     


74 days


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [31]:
import numpy as np
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
print(lists)
 

[[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
